
export class CreateCrimeDto {
    id?: string; // Optional, as it's usually generated by the database
    apiId?: number;
    caseNumber?: string;
    crimeDate?: Date;
    block?: string;
    iucr?: string;
    primaryType?: string;
    description?: string;
    locationDescription?: string;
    arrest?: boolean;
    domestic?: boolean;
    beat?: string;
    districtId: string; // Required to link the crime to a district
    ward?: number;
    communityArea?: number;
    fbiCode?: string;
    xCoordinate?: number;
    yCoordinate?: number;
    year?: number;
    updatedOn?: Date;
    latitude?: number;
    longitude?: number;
}
